# Generated by Django 4.1 on 2024-08-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fin_data_cl",
            "0002_financialdata_pricedata_remove_updatedprice_ticker_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financialratio", name="debt_to_equity_ratio",
        ),
        migrations.AddField(
            model_name="financialratio",
            name="current_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="financialratio",
            name="debt_to_equity",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="financialratio",
            name="ev_ebitda",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="financialratio",
            name="ev_sales",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="financialratio",
            name="gross_profit_margin",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="financialratio",
            name="net_profit_margin",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="financialratio",
            name="operating_profit_margin",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="financialratio",
            name="pb_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="financialratio",
            name="peg_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="financialratio",
            name="ps_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="financialratio",
            name="quick_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="financialratio",
            name="return_on_assets",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="financialratio",
            name="return_on_equity",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="financialratio",
            name="return_on_investment",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
